### ISSUE TITLE
build error due to incompatible with typescript version

### ISSUE THREAD

**Issue by abramsz** [notadd/ng-notadd#32]
ng version
------------
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.3
Node: 10.14.0
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.3
@angular/pwa                      0.12.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.3.3333
webpack                           4.28.4

ng start
-------------------------------------
$ yarn start
yarn run v1.13.0
$ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2019-02-22T04:15:14.722Z
Hash: d1cdc3821f1648cd7e5c
Time: 6944ms
chunk {main} main.js, main.js.map (main) 1.89 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 93.1 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.53 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3333 was found instead.
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...

---
It seems that the version of typescript is incompatible with angular-compiler.

**Comment by zuohuadong** [comment]
本地 ts 版本问题

**Comment by abramsz** [comment]
> 本地 ts 版本问题
> 建议使用 3.2 版本

Is it Ok for me to patch it?

**Comment by abramsz** [comment]
> 本地 ts 版本问题
> 建议使用 3.2 版本

thanks
